// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIkcBbthmdFZfL7_U-7V37xuh5B8Ifd1g',
    appId: '1:834635604088:web:f3af9af4049c1feaba8d8d',
    messagingSenderId: '834635604088',
    projectId: 'flutter-demo-17f4b',
    authDomain: 'flutter-demo-17f4b.firebaseapp.com',
    storageBucket: 'flutter-demo-17f4b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPPW6n1UyURlxdzzJ0PzW2WBAU3D11cFo',
    appId: '1:834635604088:android:3fa8175636e8a3aaba8d8d',
    messagingSenderId: '834635604088',
    projectId: 'flutter-demo-17f4b',
    storageBucket: 'flutter-demo-17f4b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCld9YSe38w-M6Crbrj-4NweVZEU6PUVVQ',
    appId: '1:834635604088:ios:d8924be10abef6daba8d8d',
    messagingSenderId: '834635604088',
    projectId: 'flutter-demo-17f4b',
    storageBucket: 'flutter-demo-17f4b.appspot.com',
    iosClientId: '834635604088-8llo8pns1jkqandl2ihqjs6c4cr0i78a.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCld9YSe38w-M6Crbrj-4NweVZEU6PUVVQ',
    appId: '1:834635604088:ios:d8924be10abef6daba8d8d',
    messagingSenderId: '834635604088',
    projectId: 'flutter-demo-17f4b',
    storageBucket: 'flutter-demo-17f4b.appspot.com',
    iosClientId: '834635604088-8llo8pns1jkqandl2ihqjs6c4cr0i78a.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWithFirebase',
  );
}
